description: >
    This defines a Port to be exposed for system management.
    It contains properties that describe a port of a switch, controller,
    chassis, or any other device that could be connected to another entity.

properties:
    - name: LinkState
      type: enum[self.LinkStates]
      default: Enabled
      description: >
          The desired link state for this interface.

    - name: LinkStatus
      type: enum[self.LinkStatusType]
      default: LinkUp
      description: >
          The desired link status for this interface.

enumerations:
    - name: LinkStates
      description: >
          Possible link states.
      values:
        - name: Disabled
          description: >
              This link is disabled.
        - name: Enabled
          description: >
              This link is enabled.
        - name: Error
          description: >
              This link is in error state.              
        - name: Unknown
          description: >
              This link state is not known.  

    - name: LinkStatusType
      description: >
          Possible link status.
      values:
        - name: LinkDown
          description: >
              The link on this interface is down.
        - name: LinkUp
          description: >
              This link on this interface is up.
        - name: NoLink
          description: >
              No physical link detected on this interface.
        - name: Starting
          description: >
              This link on this interface is starting. A physical
              link has been established, but the port is not able
              to transfer data.
        - name: Training
          description: >
              This physical link on this interface is training.
