description: >
   Implement to provide the reconfiguration permissions that restrict the users from configuring certain features from in-band (host software) interfaces.

properties:
    - name: AllowOneShotConfig
      type: boolean
      description: >
            An indication if one-shot configuration of setting by host software is allowed.  If `true`, any change to the feature via in-band APIs will not persist across hot-resets or function level resets (FLR) resets.
      errors:
          # Indicate that timeout from the device response
          - xyz.openbmc_project.Common.Error.Timeout
          # Indicate that this property is temporarily unable to be changed.
          - xyz.openbmc_project.Common.Error.Unavailable
          # Indicate a failure to apply changes to the processor.
          - xyz.openbmc_project.Common.Device.Error.WriteFailure          

    - name: AllowPersistentConfig
      type: boolean
      description: >
            An indication if persistent configuration of setting by host software is allowed. If `true`, any change to the feature via in-band APIs will persist across device resets.
      errors:
          # Indicate that timeout from the device response
          - xyz.openbmc_project.Common.Error.Timeout
          # Indicate that this property is temporarily unable to be changed.
          - xyz.openbmc_project.Common.Error.Unavailable
          # Indicate a failure to apply changes to the processor.
          - xyz.openbmc_project.Common.Device.Error.WriteFailure

    - name: AllowFLRPersistentConfig
      type: boolean
      description: >
            An indication if FLR persistent configuration of setting by host software is allowed.  If `true`, any change to the feature via in-band APIs will persist across function level resets (FLR).
      errors:
          # Indicate that timeout from the device response
          - xyz.openbmc_project.Common.Error.Timeout
          # Indicate that this property is temporarily unable to be changed.
          - xyz.openbmc_project.Common.Error.Unavailable
          # Indicate a failure to apply changes to the processor.
          - xyz.openbmc_project.Common.Device.Error.WriteFailure

